#include "WebViewEditor.h"
#include "BinaryData.h"     // generated by juce_add_binary_data

namespace punch2pen {

namespace {

// Convert a JS-safe quoted string literal from a std::string / juce::String.
juce::String jsQuote(const juce::String &s) {
  juce::String escaped;
  for (auto c : s) {
    switch (c) {
      case '\\': escaped += "\\\\"; break;
      case '"':  escaped += "\\\""; break;
      case '\n': escaped += "\\n";  break;
      case '\r': escaped += "\\r";  break;
      case '\t': escaped += "\\t";  break;
      default:
        if ((juce::juce_wchar)c < 0x20)
          escaped += juce::String::formatted("\\u%04x", (int)c);
        else
          escaped += juce::String::charToString(c);
    }
  }
  return "\"" + escaped + "\"";
}

juce::String getIndexHtml() {
  int size = 0;
  if (auto *data = BinaryData::getNamedResource("index_html", size))
    return juce::String::fromUTF8(data, size);

  // Return a minimal diagnostic page so a misconfigured build (e.g. the
  // BinaryData resource key drifted, or index.html was removed from
  // juce_add_binary_data) is visible rather than producing a silent blank
  // WebView.
  return "<html><body style='background:#1C1917;color:#FCD34D;"
         "font-family:monospace;padding:24px'>"
         "<h3>punch2pen WebView</h3>"
         "<p>BinaryData resource \"index_html\" not found. "
         "Re-run CMake configure and verify that "
         "<code>Source/ui/public/index.html</code> is listed in "
         "<code>juce_add_binary_data</code>.</p>"
         "</body></html>";
}

} // namespace

// ─────────────────────────────────────────────────────────────────────────────

WebViewEditor::WebViewEditor(Punch2PenAudioProcessor &p)
    : audioProcessor(p) {

  setSize(400, 600);

  // Build the WebBrowserComponent with native integration.
  juce::WebBrowserComponent::Options options;
  options = options
            .withBackend(juce::WebBrowserComponent::Options::Backend::webview2)
            .withWinWebView2Options(
                juce::WebBrowserComponent::Options::WinWebView2{}
                    .withBackgroundColour(juce::Colour(0xff1E1E1E)))
            .withNativeIntegrationEnabled()
            .withInitialisationData("punch2pen", juce::var(true))
            .withNativeFunction(
                "onWordClicked",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnWordClicked(args));
                })
            .withNativeFunction(
                "submitCorrection",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeSubmitCorrection(args));
                })
            .withNativeFunction(
                "onCorrectionCancelled",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnCorrectionCancelled(args));
                })
            .withNativeFunction(
                "onReady",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnReady(args));
                })
            .withResourceProvider(
                [](const juce::String &url)
                    -> std::optional<juce::WebBrowserComponent::Resource> {
                  juce::ignoreUnused(url);
                  juce::WebBrowserComponent::Resource res;
                  auto html = getIndexHtml();
                  auto utf8 = html.toRawUTF8();
                  auto len = std::strlen(utf8);
                  res.data.resize(len);
                  std::memcpy(res.data.data(), utf8, len);
                  res.mimeType = "text/html";
                  return res;
                });

  webView = std::make_unique<juce::WebBrowserComponent>(options);
  addAndMakeVisible(*webView);

  // Trigger the resource provider with any URL — content is the same.
  webView->goToURL("https://punch2pen.local/index.html");

  // Hook into IPC.
  if (auto *client = audioProcessor.getIPCClient()) {
    client->addListener(this);
    lastConnected = client->isConnected();
  }

  startTimerHz(30);
}

WebViewEditor::~WebViewEditor() {
  stopTimer();
  if (auto *client = audioProcessor.getIPCClient()) {
    client->removeListener(this);
  }
}

void WebViewEditor::paint(juce::Graphics &g) {
  g.fillAll(juce::Colour(0xff1E1E1E));
}

void WebViewEditor::resized() {
  if (webView)
    webView->setBounds(getLocalBounds());
}

// ── 30Hz tick ───────────────────────────────────────────────────────────────
void WebViewEditor::timerCallback() {
  auto transport = audioProcessor.getTransportPosition();

  double sampleRate = audioProcessor.getSampleRate();
  if (sampleRate <= 0.0)
    sampleRate = 48000.0;

  double currentSamplePosition =
      transport.ppq * (60.0 / juce::jmax(1.0, transport.bpm)) * sampleRate;
  jsUpdatePlayhead(currentSamplePosition);

  double beatsPerBar = (double)juce::jmax(1, (int)transport.timeSigNum);
  int bar  = (int)(transport.ppq / beatsPerBar) + 1;
  int beat = (int)std::fmod(transport.ppq, beatsPerBar) + 1;
  if (bar != lastBar || beat != lastBeat) {
    jsUpdatePosition(bar, beat);
    lastBar = bar;
    lastBeat = beat;
  }

  // Derive the canonical state from processor flags.
  juce::String state;
  if (!lastConnected)              state = "disconnected";
  else if (transport.isRecording)  state = "recording";
  else if (transport.isPlaying)    state = "playback";
  else                             state = "idle";
  if (state != lastState) {
    if (state == "recording" && lastState != "recording") {
      ++takeGeneration;
      streamCursorSample = 0.0;
      runJs("window.resetTranscript();");
    }
    jsSetState(state);
    lastState = state;
  }
}

// ── IPCClient::Listener ─────────────────────────────────────────────────────
void WebViewEditor::onTranscriptionReceived(const std::string &text) {
  juce::Component::SafePointer<WebViewEditor> safeThis(this);
  auto generation = takeGeneration.load();
  juce::MessageManager::callAsync([safeThis, text, generation] {
    if (safeThis == nullptr) return;
    if (safeThis->takeGeneration.load() != generation) return;
    safeThis->streamCursorSample += 4800.0;
    double start = safeThis->streamCursorSample;
    double end   = start + 4800.0;
    int bar = juce::jmax(1, safeThis->lastBar);
    safeThis->jsAppendWord(juce::String(text), start, end, bar);
  });
}

void WebViewEditor::onStatusChanged(bool connected) {
  juce::Component::SafePointer<WebViewEditor> safeThis(this);
  juce::MessageManager::callAsync([safeThis, connected] {
    if (safeThis == nullptr) return;
    safeThis->lastConnected = connected;
    safeThis->jsSetConnectionStatus(connected);
  });
}

// ── JS dispatch ─────────────────────────────────────────────────────────────
void WebViewEditor::runJs(const juce::String &script) {
  if (!webView) return;
  if (!pageReady) {
    queuedJs.add(script);
    return;
  }
  webView->evaluateJavascript(script);
}

void WebViewEditor::jsAppendWord(const juce::String &text,
                                 double startSample, double endSample, int bar) {
  runJs("window.appendWord("
        + jsQuote(text) + ","
        + juce::String(startSample) + ","
        + juce::String(endSample) + ","
        + juce::String(bar) + ");");
}

void WebViewEditor::jsUpdatePlayhead(double sample) {
  runJs("window.updatePlayhead(" + juce::String(sample) + ");");
}

void WebViewEditor::jsUpdatePosition(int bar, int beat) {
  runJs("window.updatePosition(" + juce::String(bar) + ","
        + juce::String(beat) + ");");
}

void WebViewEditor::jsSetConnectionStatus(bool connected) {
  runJs(juce::String("window.setConnectionStatus(")
        + (connected ? "true" : "false") + ");");
}

void WebViewEditor::jsSetState(const juce::String &state) {
  runJs("window.setState(" + jsQuote(state) + ");");
}

// ── Native callbacks from the page ──────────────────────────────────────────
juce::var WebViewEditor::nativeOnReady(const juce::Array<juce::var> &) {
  pageReady = true;
  for (const auto &js : queuedJs) {
    if (webView) webView->evaluateJavascript(js);
  }
  queuedJs.clear();
  // Push current connection state on first ready.
  jsSetConnectionStatus(lastConnected);
  return {};
}

juce::var WebViewEditor::nativeOnWordClicked(const juce::Array<juce::var> &args) {
  if (args.size() < 1) return {};
  auto word = args[0].toString();
  int x = args.size() > 1 ? (int)args[1] : 20;
  int y = args.size() > 2 ? (int)args[2] : 100;
  // Tell the page to open its correction popup.
  runJs("window.showCorrection("
        + jsQuote(word) + ","
        + juce::String(x) + ","
        + juce::String(y) + ");");
  return {};
}

juce::var WebViewEditor::nativeSubmitCorrection(const juce::Array<juce::var> &args) {
  if (args.size() < 2) return {};
  auto orig = args[0].toString().toStdString();
  auto next = args[1].toString().toStdString();
  if (!next.empty() && next != orig) {
    if (auto *client = audioProcessor.getIPCClient())
      client->sendCorrection(orig, next);
  }
  return {};
}

juce::var WebViewEditor::nativeOnCorrectionCancelled(const juce::Array<juce::var> &) {
  return {};
}

} // namespace punch2pen
