#include "WebViewEditor.h"
#include "BinaryData.h"     // generated by juce_add_binary_data

#include <cmath>

namespace punch2pen {

namespace {

juce::String getIndexHtml() {
  int size = 0;
  auto *data = BinaryData::getNamedResource("index_html", size);
  jassert(data != nullptr);
  if (data != nullptr)
    return juce::String::fromUTF8(data, size);

  return {};
}

} // namespace

// ─────────────────────────────────────────────────────────────────────────────

WebViewEditor::WebViewEditor(Punch2PenAudioProcessor &p)
    : audioProcessor(p) {

  setSize(400, 600);

  // Build the WebBrowserComponent with native integration.
  juce::WebBrowserComponent::Options options;
  options = options
            .withNativeIntegrationEnabled()
            .withInitialisationData("punch2pen", juce::var(true))
            .withNativeFunction(
                "onWordClicked",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnWordClicked(args));
                })
            .withNativeFunction(
                "submitCorrection",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeSubmitCorrection(args));
                })
            .withNativeFunction(
                "onCorrectionCancelled",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnCorrectionCancelled(args));
                })
            .withNativeFunction(
                "onReady",
                [this](const juce::Array<juce::var> &args,
                       auto completion) {
                  completion(nativeOnReady(args));
                })
            .withResourceProvider(
                [](const juce::String &url)
                    -> std::optional<juce::WebBrowserComponent::Resource> {
                  juce::ignoreUnused(url);
                  juce::WebBrowserComponent::Resource res;
                  auto html = getIndexHtml();
                  auto utf8 = html.toRawUTF8();
                  auto len = std::strlen(utf8);
                  res.data.resize(len);
                  std::memcpy(res.data.data(), utf8, len);
                  res.mimeType = "text/html";
                  return res;
                });

#if JUCE_WINDOWS
  options = options
                .withBackend(
                    juce::WebBrowserComponent::Options::Backend::webview2)
                .withWinWebView2Options(
                    juce::WebBrowserComponent::Options::WinWebView2{}
                        .withBackgroundColour(juce::Colour(0xff1E1E1E)));
#endif

  webView = std::make_unique<juce::WebBrowserComponent>(options);
  addAndMakeVisible(*webView);
  webView->setBounds(getLocalBounds());

  webView->goToURL(juce::WebBrowserComponent::getResourceProviderRoot());

  // Hook into IPC.
  if (auto *client = audioProcessor.getIPCClient()) {
    client->addListener(this);
    lastConnected = client->isConnected();
  }

  startTimerHz(30);
}

WebViewEditor::~WebViewEditor() {
  stopTimer();
  if (auto *client = audioProcessor.getIPCClient()) {
    client->removeListener(this);
  }
}

void WebViewEditor::paint(juce::Graphics &g) {
  g.fillAll(juce::Colour(0xff1E1E1E));
}

void WebViewEditor::resized() {
  if (webView)
    webView->setBounds(getLocalBounds());
}

// ── 30Hz tick ───────────────────────────────────────────────────────────────
void WebViewEditor::timerCallback() {
  auto transport = audioProcessor.getTransportPosition();

  double sampleRate = audioProcessor.getSampleRate();
  if (sampleRate <= 0.0)
    sampleRate = 48000.0;

  double currentSamplePosition =
      transport.ppq * (60.0 / juce::jmax(1.0, transport.bpm)) * sampleRate;
  jsUpdatePlayhead(currentSamplePosition);

  if (transport.bar != lastBar || transport.beat != lastBeat) {
    jsUpdatePosition(transport.bar, transport.beat);
    lastBar = transport.bar;
    lastBeat = transport.beat;
  }

  if (audioProcessor.consumePendingTransportStop()) {
    if (auto *c = audioProcessor.getIPCClient())
      c->sendTransportStop();
  }

  auto *client = audioProcessor.getIPCClient();
  const bool connected = client != nullptr && client->isConnected();
  if (connected != lastConnected) {
    lastConnected = connected;
    jsSetConnectionStatus(connected);
  }

  // Derive the canonical state from processor flags.
  juce::String state;
  if (!lastConnected)              state = "disconnected";
  else if (transport.isRecording)  state = "recording";
  else if (transport.isPlaying)    state = "playback";
  else                             state = "idle";
  if (state != lastState) {
    if (state == "recording" && lastState != "recording") {
      ++takeGeneration;
      streamCursorSample = 0.0;
      runJs("window.resetTranscript();");
    }
    jsSetState(state);
    lastState = state;
  }
}

// ── IPCClient::Listener ─────────────────────────────────────────────────────
void WebViewEditor::onTranscriptionReceived(const std::string &text) {
  juce::Component::SafePointer<WebViewEditor> safeThis(this);
  auto generation = takeGeneration.load();
  juce::MessageManager::callAsync([safeThis, text, generation] {
    if (safeThis == nullptr) return;
    if (safeThis->takeGeneration.load() != generation) return;
    safeThis->streamCursorSample += 4800.0;
    double start = safeThis->streamCursorSample;
    double end   = start + 4800.0;
    int bar = juce::jmax(1, safeThis->lastBar);
    safeThis->jsAppendWord(juce::String(text), start, end, bar);
  });
}

void WebViewEditor::onStatusChanged(bool connected) {
  juce::Component::SafePointer<WebViewEditor> safeThis(this);
  juce::MessageManager::callAsync([safeThis, connected] {
    if (safeThis == nullptr) return;
    safeThis->lastConnected = connected;
    safeThis->jsSetConnectionStatus(connected);
  });
}

// ── JS dispatch ─────────────────────────────────────────────────────────────
void WebViewEditor::runJs(const juce::String &script, bool queueIfPending) {
  if (!webView) return;
  if (!pageReady) {
    // Only buffer scripts the caller explicitly wants replayed once the page
    // is ready (e.g. resetTranscript, setState). Transient 30Hz updates pass
    // queueIfPending=false so they don't accumulate if the WebView never
    // initialises.
    if (queueIfPending)
      queuedJs.add(script);
    return;
  }
  webView->evaluateJavascript(script);
}

void WebViewEditor::jsAppendWord(const juce::String &text,
                                 double startSample, double endSample, int bar) {
  // Words arrive on IPC at unbounded rate; don't buffer them if the page
  // isn't ready (resetTranscript will be replayed instead).
  runJs("window.appendWord("
        + juce::JSON::toString(juce::var(text)) + ","
        + juce::String(startSample) + ","
        + juce::String(endSample) + ","
        + juce::String(bar) + ");",
        /*queueIfPending=*/false);
}

void WebViewEditor::jsUpdatePlayhead(double sample) {
  if (std::abs(sample - lastPlayheadSample) < 0.1)
    return;

  lastPlayheadSample = sample;
  runJs("window.updatePlayhead(" + juce::String(sample) + ");",
        /*queueIfPending=*/false);
}

void WebViewEditor::jsUpdatePosition(int bar, int beat) {
  // Changes on every beat — never buffer.
  runJs("window.updatePosition(" + juce::String(bar) + ","
        + juce::String(beat) + ");",
        /*queueIfPending=*/false);
}

void WebViewEditor::jsSetConnectionStatus(bool connected) {
  runJs(juce::String("window.setConnectionStatus(")
        + (connected ? "true" : "false") + ");");
}

void WebViewEditor::jsSetState(const juce::String &state) {
  runJs("window.setState(" + juce::JSON::toString(juce::var(state)) + ");");
}

// ── Native callbacks from the page ──────────────────────────────────────────
juce::var WebViewEditor::nativeOnReady(const juce::Array<juce::var> &) {
  pageReady = true;
  for (const auto &js : queuedJs) {
    if (webView) webView->evaluateJavascript(js);
  }
  queuedJs.clear();
  // Push current connection state on first ready.
  jsSetConnectionStatus(lastConnected);
  return {};
}

juce::var WebViewEditor::nativeOnWordClicked(const juce::Array<juce::var> &args) {
  if (args.size() < 1) return {};
  auto word = args[0].toString();
  int x = args.size() > 1 ? (int)args[1] : 20;
  int y = args.size() > 2 ? (int)args[2] : 100;
  // Tell the page to open its correction popup.
  runJs("window.showCorrection("
        + juce::JSON::toString(juce::var(word)) + ","
        + juce::String(x) + ","
        + juce::String(y) + ");");
  return {};
}

juce::var WebViewEditor::nativeSubmitCorrection(const juce::Array<juce::var> &args) {
  if (args.size() < 2) return {};
  auto orig = args[0].toString().toStdString();
  auto next = args[1].toString().toStdString();
  if (!next.empty() && next != orig) {
    if (auto *client = audioProcessor.getIPCClient())
      client->sendCorrection(orig, next);
  }
  return {};
}

juce::var WebViewEditor::nativeOnCorrectionCancelled(const juce::Array<juce::var> &) {
  return {};
}

} // namespace punch2pen
