#!/usr/bin/env node
// Bundles design/shaders/src into one offline ESM file, design/shaders/p2p-shaders.js.
// The plugin WebView loads nothing from the network, so the runtime ships vendored.
//   cd design/shaders && npm ci && node build.mjs
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, '..', 'tokens', 'tokens.json'), 'utf8'));

// Flatten the colors the presets use into T['graphite-900'], T['green-400'], T.wait …
const get = (path) => path.split('.').reduce((n, k) => n?.[k], tokens);
const resolve = (v) => (typeof v === 'string' && /^\{.+\}$/.test(v) ? resolve(get(v.slice(1, -1)).$value) : v);
const T = {};
for (const [k, v] of Object.entries(tokens.color.graphite)) if (!k.startsWith('$')) T[`graphite-${k}`] = v.$value;
for (const [k, v] of Object.entries(tokens.color.green)) if (!k.startsWith('$')) T[`green-${k}`] = v.$value;
for (const [k, v] of Object.entries(tokens.semantic)) if (!k.startsWith('$')) T[k] = resolve(v.$value);
writeFileSync(
  join(here, 'src', 'tokens.generated.js'),
  `// Generated by design/shaders/build.mjs from design/tokens/tokens.json. Do not edit.\nexport const T = ${JSON.stringify(T, null, 2)};\n`,
);

const pkg = JSON.parse(readFileSync(join(here, 'node_modules', '@paper-design', 'shaders', 'package.json'), 'utf8'));
await build({
  entryPoints: [join(here, 'src', 'p2p-shaders.js')],
  outfile: join(here, 'p2p-shaders.js'),
  bundle: true,
  format: 'esm',
  minify: true,
  target: ['safari15', 'chrome100'],
  legalComments: 'none',
  banner: {
    js: `/* Punch2Pen shader runtime. Bundles Paper Shaders ${pkg.version} (Apache-2.0, https://github.com/paper-design/shaders). See design/shaders/NOTICE. */`,
  },
});
console.log(`built design/shaders/p2p-shaders.js with @paper-design/shaders ${pkg.version}`);
