#!/usr/bin/env node
// Builds design/tokens/tokens.css from design/tokens/tokens.json and prints a
// contrast report for the pairs the plugin and site actually use.
//   node design/tokens/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const get = (path) => path.split('.').reduce((node, key) => node?.[key], tokens);
const resolve = (value) => {
  if (typeof value !== 'string') return value;
  const alias = value.match(/^\{(.+)\}$/);
  if (!alias) return value;
  const target = get(alias[1]);
  if (!target || !('$value' in target)) throw new Error(`Unresolved alias ${value}`);
  return resolve(target.$value);
};
const leaves = (node, path = []) =>
  Object.entries(node)
    .filter(([k]) => !k.startsWith('$'))
    .flatMap(([k, v]) => (v && typeof v === 'object' && '$value' in v ? [[[...path, k], v]] : v && typeof v === 'object' ? leaves(v, [...path, k]) : []));
const css = (v) => (Array.isArray(v) ? `cubic-bezier(${v.join(', ')})` : String(v));

const lines = [];
const block = (title, entries) => {
  lines.push(`\n  /* ${title} */`);
  for (const [name, token] of entries) {
    const note = token.$description ? `  /* ${token.$description.replace(/\*\//g, '')} */` : '';
    lines.push(`  --${name}: ${css(resolve(token.$value))};${note}`);
  }
};

block('Primitives: graphite', leaves(tokens.color.graphite).map(([p, t]) => [`graphite-${p.at(-1)}`, t]));
block('Primitives: red (hue 1; 600 is the brand red from the 2PEN logo)', leaves(tokens.color.red).map(([p, t]) => [`red-${p.at(-1)}`, t]));
block('Roles. Names match the shipped plugin and site CSS.', leaves(tokens.semantic).map(([p, t]) => [p.at(-1), t]));
block('Type', [
  ['display', tokens.font.display],
  ['sans', tokens.font.sans],
  ['mono', tokens.font.mono],
  ['display-stretch', tokens['font-stretch'].display],
  ...leaves(tokens.size.plugin).map(([p, t]) => [`fs-plugin-${p.at(-1)}`, t]),
  ...leaves(tokens.size.site).map(([p, t]) => [`fs-${p.at(-1)}`, t]),
]);
block('Space', leaves(tokens.space).map(([p, t]) => [`space-${p.at(-1)}`, t]));
block('Radius', [...leaves(tokens.radius).map(([p, t]) => [`radius-${p.at(-1)}`, t]), ['radius', tokens.radius.sm]]);
block('Motion', leaves(tokens.motion).map(([p, t]) => [`t-${p.at(-1)}`, t]));
block('Shadow', leaves(tokens.shadow).map(([p, t]) => [`shadow-${p.at(-1)}`, t]));
block('Lyric: Temporal Hierarchy', [
  ['past', tokens.lyric.past],
  ['upcoming', tokens.lyric.upcoming],
  ['active', tokens.lyric.active],
  ['lyric-lh', tokens.lyric['line-height']],
  ['focal-play', tokens.lyric['focal-play']],
  ['focal-rec', tokens.lyric['focal-rec']],
  ['lyric-size', tokens.size.plugin.lyric],
  ['title-size', tokens.size.plugin.title],
]);
block('Layout', leaves(tokens.layout).map(([p, t]) => [p.at(-1), t]));

const out = `/*
  Punch2Pen tokens. Generated by design/tokens/build.mjs from tokens.json.
  Do not edit by hand.

  Direction: the 2PEN logo. Brick red and a legal-yellow pad on Open graphite.
  Mono is the punch (clock, labels). Sans is the words. Archivo is the poster.
  Brand red is a fill with white type. REC (#FF453A) is a dot or badge only.
  PLAY and LIVE are white. Focus rings are white.
*/
:root {
  color-scheme: dark;${lines.join('\n')}
}
`;
writeFileSync(join(here, 'tokens.css'), out);

// Contrast report --------------------------------------------------------
const rgb = (c) => {
  const s = resolve(c);
  if (s.startsWith('#')) return [1, 3, 5].map((i) => parseInt(s.slice(i, i + 2), 16) / 255).concat(1);
  const m = s.match(/rgba?\(([^)]+)\)/)[1].split(',').map(Number);
  return [m[0] / 255, m[1] / 255, m[2] / 255, m[3] ?? 1];
};
const over = (fg, bg) => fg.slice(0, 3).map((x, i) => x * fg[3] + bg[i] * (1 - fg[3]));
const lum = ([r, g, b]) => [r, g, b].map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)).reduce((a, c, i) => a + c * [0.2126, 0.7152, 0.0722][i], 0);
const ratio = (fg, bg) => {
  const b = rgb(bg).slice(0, 3);
  const f = over(rgb(fg), b);
  const [x, y] = [lum(f), lum(b)];
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05);
};
const S = tokens.semantic;
const pairs = [
  ['ink', 'bg-pane'], ['ink-2', 'bg-pane'], ['ink-3', 'bg-pane'], ['ink-3', 'bg-chrome'], ['ink-3', 'bg-raised'],
  ['accent', 'bg-pane'], ['accent', 'bg-chrome'], ['accent', 'bg-raised'], ['accent-strong', 'bg-deep'], ['accent-strong', 'bg-chrome'], ['accent-ink', 'accent-fill'], ['accent-ink', 'accent-fill-hover'],
  ['rec', 'bg-chrome'], ['wait', 'bg-chrome'], ['pad-ink', 'pad-paper'], ['pad-ink-2', 'pad-paper'], ['pad-accent', 'pad-paper'],
];
console.log('wrote design/tokens/tokens.css\n\ncontrast (WCAG 2.x)');
for (const [fg, bg] of pairs) {
  const r = ratio(S[fg].$value, S[bg].$value);
  console.log(`  ${fg.padEnd(17)} on ${bg.padEnd(17)} ${r.toFixed(2).padStart(5)}:1  ${r >= 4.5 ? 'AA text' : r >= 3 ? 'AA large/UI' : 'decorative'}`);
}
